/**
 * This file was generated by the JPA Modeler
 */ 

package fr.trendev.postalhelper.entities;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * @author jsie
 */

@Entity
@Table(name="POSTAL_CODE_FR")
@IdClass(PostalCodeFRPK.class)
@XmlRootElement
public class PostalCodeFR { 

    @Id
    @NotNull
    private String code;

    @Id
    @NotNull
    private String town;

    @Basic
    private String gpsCoords;


    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getTown() {
        return this.town;
    }

    public void setTown(String town) {
        this.town = town;
    }

    public String getGpsCoords() {
        return this.gpsCoords;
    }

    public void setGpsCoords(String gpsCoords) {
        this.gpsCoords = gpsCoords;
    }


}
