/**
 * This file was generated by the JPA Modeler
 */
package fr.trendev.postalhelper.entities;

import fr.trendev.postalhelper.constraints.NotBlank;
import fr.trendev.postalhelper.constraints.NotEmpty;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * @author jsie
 */
@Entity
@Table(name = "POSTAL_CODE_FR")
@IdClass(PostalCodeFRPK.class)
public class PostalCodeFR {

    @Id
    @NotBlank
    @NotNull
    @Size(min = 5, max = 5)
    private String code;

    @Id
    @NotBlank
    @NotEmpty
    @NotNull
    private String town;

    @Basic
    private String gpsCoords;

    public PostalCodeFR() {
    }

    public PostalCodeFR(String code, String town) {
        this.code = code;
        this.town = town;
    }

    public PostalCodeFR(String code, String town, String gpsCoords) {
        this.code = code;
        this.town = town;
        this.gpsCoords = gpsCoords;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getTown() {
        return this.town;
    }

    public void setTown(String town) {
        this.town = town;
    }

    public String getGpsCoords() {
        return this.gpsCoords;
    }

    public void setGpsCoords(String gpsCoords) {
        this.gpsCoords = gpsCoords;
    }

    @Override
    public String toString() {
        return "PostalCodeFR{" + " code=" + code + ", town=" + town + '}';
    }

}
